/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vue;



import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTextField;
import javax.swing.JToggleButton;

/**
 *
 * @author almamy
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        this.setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        framePanel = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        usernamefield = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        forget_pass_word = new javax.swing.JToggleButton();
        pass_word_field = new javax.swing.JPasswordField();
        btn_log_up = new javax.swing.JButton();
        btn_Log_in = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(86, 12, 12));

        framePanel.setFocusable(false);
        framePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        title.setFont(new java.awt.Font("Umpush", 1, 25)); // NOI18N
        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setText("Boulangerie Patisserie Buruso");
        framePanel.add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 380, 51));

        jLabel3.setFont(new java.awt.Font("Liberation Sans", 1, 20)); // NOI18N
        jLabel3.setText("User name :");
        framePanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, 30));

        usernamefield.setFont(new java.awt.Font("Liberation Sans", 0, 15)); // NOI18N
        usernamefield.setBorder(null);
        framePanel.add(usernamefield, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 180, 20));

        jLabel4.setFont(new java.awt.Font("Liberation Sans", 1, 20)); // NOI18N
        jLabel4.setText("Pass word :");
        framePanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, 30));

        forget_pass_word.setBackground(new java.awt.Color(242, 242, 242));
        forget_pass_word.setText("Pass words to forget ?");
        forget_pass_word.setBorder(null);
        forget_pass_word.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                forget_pass_wordActionPerformed(evt);
            }
        });
        framePanel.add(forget_pass_word, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 220, -1, -1));

        pass_word_field.setFont(new java.awt.Font("Liberation Sans", 0, 15)); // NOI18N
        pass_word_field.setBorder(null);
        framePanel.add(pass_word_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, 180, 20));

        btn_log_up.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        btn_log_up.setText("Sign up");
        btn_log_up.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_log_up.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_log_upActionPerformed(evt);
            }
        });
        framePanel.add(btn_log_up, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 300, 119, 36));

        btn_Log_in.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        btn_Log_in.setText("Log in");
        btn_Log_in.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Log_inActionPerformed(evt);
            }
        });
        framePanel.add(btn_Log_in, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 300, 119, 36));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(framePanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 436, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(framePanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void forget_pass_wordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_forget_pass_wordActionPerformed
        // TODO add your handling code here:
        PasswordForget forget = new PasswordForget();
        forget.show();
        dispose();
    }//GEN-LAST:event_forget_pass_wordActionPerformed

    private void btn_Log_inActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Log_inActionPerformed
        File file = new File("/home/almamy/Documents/MyProject/Buruso/src/main/java/modele/authentification/LogUp.txt");
        if(!file.exists()){
            try {
                file.createNewFile();
            } catch (IOException ex) {
                Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{   
            try {
                Scanner sc = new Scanner(file);
                String str = "";
                String str2 = "";
                String use = this.usernamefield.getText();
                String pass = this.pass_word_field.getText();
                while(sc.hasNext()){
                    String mot = sc.next();
                    String mot2 = sc.next();

                    if(mot.equals(use)){System.out.println(mot);
                        str2 = mot;
                    }
                    if(mot2.equals(pass)){  System.out.println(mot2);
                        str = mot2;
                    }
                }

                   if((use).equals("") || (pass).equals("")){
                        JOptionPane.showMessageDialog(this, "Please fill in the fields correctly");

                    }else if (str2.equals((use))  && str.equals((pass)) ) {
                        JOptionPane.showMessageDialog(this, "Connexion is success");
                        Log_up log_up = new Log_up();
                        log_up.show();
                        dispose();

                    } else {
                        JOptionPane.showMessageDialog(this, "Your username or passWord is avalable");
                    }
               } catch (FileNotFoundException ex) {
                Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
    }//GEN-LAST:event_btn_Log_inActionPerformed

    private void btn_log_upActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_log_upActionPerformed
        // TODO add your handling code here:
        Log_up log = new Log_up();
        log.show();
        dispose();
    }//GEN-LAST:event_btn_log_upActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Log_in;
    private javax.swing.JButton btn_log_up;
    private javax.swing.JToggleButton forget_pass_word;
    private javax.swing.JPanel framePanel;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPasswordField pass_word_field;
    private javax.swing.JLabel title;
    private javax.swing.JTextField usernamefield;
    // End of variables declaration//GEN-END:variables

    //Getter and Setter 
    public JButton getBtn_Log_in() {
        return btn_Log_in;
    }

    public void setBtn_Log_in(JButton btn_Log_in) {
        this.btn_Log_in = btn_Log_in;
    }

    public JButton getBtn_log_up() {
        return btn_log_up;
    }

    public void setBtn_log_up(JButton btn_log_up) {
        this.btn_log_up = btn_log_up;
    }

    public JToggleButton getForget_pass_word() {
        return forget_pass_word;
    }

    public void setForget_pass_word(JToggleButton forget_pass_word) {
        this.forget_pass_word = forget_pass_word;
    }

    public JPasswordField getPass_word_field() {
        return pass_word_field;
    }

    public void setPass_word_field(JPasswordField pass_word_field) {
        this.pass_word_field = pass_word_field;
    }

    public JTextField getUsernamefield() {
        return usernamefield;
    }

    public void setUsernamefield(JTextField usernamefield) {
        this.usernamefield = usernamefield;
    }

}
