/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vue;

/**
 *
 * @author almamy
 */
public class Seconde_Jlebal extends javax.swing.JFrame {

    /**
     * Creates new form Seconde_Jlebal
     */
    public Seconde_Jlebal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        passworLabel = new javax.swing.JLabel();
        forget_pass_word = new javax.swing.JToggleButton();
        passwordfield = new javax.swing.JPasswordField();
        btn_log_up = new javax.swing.JButton();
        usernameLabel = new javax.swing.JLabel();
        title = new javax.swing.JLabel();
        btn_Log_in = new javax.swing.JButton();
        usernameField = new javax.swing.JTextField();

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vue/BgLogin.png"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        passworLabel.setFont(new java.awt.Font("Liberation Sans", 1, 20)); // NOI18N
        passworLabel.setForeground(new java.awt.Color(249, 181, 5));
        passworLabel.setText("Pass word :");
        getContentPane().add(passworLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 160, -1, 30));

        forget_pass_word.setBackground(new java.awt.Color(69, 30, 34));
        forget_pass_word.setForeground(new java.awt.Color(249, 181, 5));
        forget_pass_word.setText("Pass words to forget ?");
        forget_pass_word.setBorder(null);
        getContentPane().add(forget_pass_word, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 210, -1, 20));
        getContentPane().add(passwordfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 160, 190, 30));

        btn_log_up.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        btn_log_up.setForeground(new java.awt.Color(249, 181, 5));
        btn_log_up.setText("Sign up");
        getContentPane().add(btn_log_up, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 260, 119, 36));

        usernameLabel.setFont(new java.awt.Font("Liberation Sans", 1, 20)); // NOI18N
        usernameLabel.setForeground(new java.awt.Color(249, 181, 5));
        usernameLabel.setText("User name :");
        getContentPane().add(usernameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 100, -1, 30));

        title.setFont(new java.awt.Font("Umpush", 1, 32)); // NOI18N
        title.setForeground(new java.awt.Color(249, 181, 5));
        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setText("Boulangerie Patisserie Buruso");
        getContentPane().add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, 480, 51));

        btn_Log_in.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        btn_Log_in.setForeground(new java.awt.Color(249, 181, 5));
        btn_Log_in.setText("Log in");
        getContentPane().add(btn_Log_in, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 260, 119, 36));
        getContentPane().add(usernameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 100, 190, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Seconde_Jlebal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Seconde_Jlebal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Seconde_Jlebal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Seconde_Jlebal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Seconde_Jlebal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Log_in;
    private javax.swing.JButton btn_log_up;
    private javax.swing.JToggleButton forget_pass_word;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel passworLabel;
    private javax.swing.JPasswordField passwordfield;
    private javax.swing.JLabel title;
    private javax.swing.JTextField usernameField;
    private javax.swing.JLabel usernameLabel;
    // End of variables declaration//GEN-END:variables
}
