/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package modele.authentification;

import modele.authentification.Login;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.Arrays;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author almamy
 */
public class Log_up extends javax.swing.JFrame {

    /**
     * Creates new form Log_up
     */
    public Log_up() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        jPanel1 = new javax.swing.JPanel();
        firtsNameField = new javax.swing.JTextField();
        firstNamelabel = new javax.swing.JLabel();
        lastNameLabel = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();
        lastNameField = new javax.swing.JTextField();
        emailField = new javax.swing.JTextField();
        passwordLabel = new javax.swing.JLabel();
        telLabel = new javax.swing.JLabel();
        telField = new javax.swing.JTextField();
        signinPasswordfield = new javax.swing.JPasswordField();
        passwordConfirmed = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        btnValidated = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        jScrollPane1.setViewportView(jEditorPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        firtsNameField.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.add(firtsNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 82, 143, -1));

        firstNamelabel.setBackground(new java.awt.Color(255, 255, 255));
        firstNamelabel.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        firstNamelabel.setForeground(new java.awt.Color(255, 255, 255));
        firstNamelabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        firstNamelabel.setText("Firs name: ");
        jPanel1.add(firstNamelabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 85, 78, -1));

        lastNameLabel.setBackground(new java.awt.Color(255, 255, 255));
        lastNameLabel.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        lastNameLabel.setForeground(new java.awt.Color(255, 255, 255));
        lastNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lastNameLabel.setText("Last name: ");
        jPanel1.add(lastNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 124, 90, 24));

        emailLabel.setBackground(new java.awt.Color(255, 255, 255));
        emailLabel.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        emailLabel.setForeground(new java.awt.Color(255, 255, 255));
        emailLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        emailLabel.setText("Email: ");
        jPanel1.add(emailLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 173, 78, 24));

        lastNameField.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.add(lastNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 124, 143, -1));

        emailField.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.add(emailField, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 173, 143, -1));

        passwordLabel.setBackground(new java.awt.Color(255, 255, 255));
        passwordLabel.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        passwordLabel.setForeground(new java.awt.Color(255, 255, 255));
        passwordLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        passwordLabel.setText("PassWord:");
        jPanel1.add(passwordLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(296, 124, 78, 24));

        telLabel.setBackground(new java.awt.Color(255, 255, 255));
        telLabel.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        telLabel.setForeground(new java.awt.Color(255, 255, 255));
        telLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        telLabel.setText("Tel:");
        jPanel1.add(telLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(296, 82, 78, 24));

        telField.setBackground(new java.awt.Color(204, 204, 204));
        telField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telFieldActionPerformed(evt);
            }
        });
        jPanel1.add(telField, new org.netbeans.lib.awtextra.AbsoluteConstraints(392, 82, 143, -1));

        signinPasswordfield.setBackground(new java.awt.Color(204, 204, 204));
        signinPasswordfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signinPasswordfieldActionPerformed(evt);
            }
        });
        jPanel1.add(signinPasswordfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(392, 124, 143, -1));

        passwordConfirmed.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.add(passwordConfirmed, new org.netbeans.lib.awtextra.AbsoluteConstraints(392, 173, 143, -1));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Confirmed:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(296, 176, -1, -1));

        btnValidated.setBackground(new java.awt.Color(242, 242, 242));
        btnValidated.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        btnValidated.setForeground(new java.awt.Color(51, 51, 51));
        btnValidated.setText("Validated");
        btnValidated.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnValidatedActionPerformed(evt);
            }
        });
        jPanel1.add(btnValidated, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 241, 122, 33));

        btnCancel.setBackground(new java.awt.Color(242, 242, 242));
        btnCancel.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        btnCancel.setForeground(new java.awt.Color(51, 51, 51));
        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        jPanel1.add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(392, 241, 122, 33));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Liberation Sans", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Sing in");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 6, 233, 44));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 330));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void telFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telFieldActionPerformed

    private void signinPasswordfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signinPasswordfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_signinPasswordfieldActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        Login log = new Login();
        log.show();
        dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnValidatedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnValidatedActionPerformed
        // TODO add your handling code here:
        
          File file = new File("/home/almamy/Documents/MyProject/Buruso/src/main/java/modele/authentification/LogUp.txt");
        
       
        if(!file.exists()){
            try {
                file.createNewFile();
            } catch (IOException ex) {
                Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{
                String[] listField = {this.firtsNameField.getText(), this.lastNameField.getText(),
                                this.emailField.getText(), this.telField.getText(),
                                this.signinPasswordfield.getText(), this.passwordConfirmed.getText()};
                System.out.println(Arrays.toString(listField));
            try {
                    Scanner sc = new Scanner(file);
                    String str = "";
                    String pass = emailvalidate(this.emailField.getText());
                    if(pass == null){
                          JOptionPane.showMessageDialog(this, "Veuillez entrez une adresse email valide");
                    }else{
                                while(sc.hasNext()){
                                    String mot = sc.next();

                                    if(mot.equals(pass)){
                                        str = mot;
                                    }
                                }   
                                System.out.print("Str valeur: " + str);
                                if(str.equals(pass)){
                                    JOptionPane.showMessageDialog(this, "Your already have an account ");
                                }else{


                                FileOutputStream fos = new FileOutputStream(file, true);
                                 fos.write("\n".getBytes());
                                for(String ls : listField){
                                      fos.write((ls + " ").getBytes());
                                    }

                                fos.close();

                                Login log = new Login();
                                log.show();
                                dispose();       
                        }
                    }
                 
            } catch (IOException ex) {
                Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
       
    }//GEN-LAST:event_btnValidatedActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Log_up.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Log_up.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Log_up.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Log_up.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Log_up().setVisible(true);
            }
        });
    }
    public  String emailvalidate(String email){
            if(email == null || email.isEmpty()){
                return null;
            }
            String emailRegex = "^[a-zA-Z0-9_+&*-]+(?:\\."+"[a-zA-Z0-9_+&*-]+)*@"+ "(?:[a-zA-Z0-9-]+\\.)+[a-zA-A]{2,7}$";
        Pattern pattern = Pattern.compile(emailRegex);
        if(pattern.matcher(email).matches()){
            return email;
        }else{
           
            return null;
        }
            
        }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnValidated;
    private javax.swing.JTextField emailField;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JLabel firstNamelabel;
    private javax.swing.JTextField firtsNameField;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField lastNameField;
    private javax.swing.JLabel lastNameLabel;
    private javax.swing.JPasswordField passwordConfirmed;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JPasswordField signinPasswordfield;
    private javax.swing.JTextField telField;
    private javax.swing.JLabel telLabel;
    // End of variables declaration//GEN-END:variables

    
}
