/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package modele.authentification;

import modele.authentification.Login;
import java.io.File;
import java.io.FileNotFoundException;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.Properties;
import java.util.Random;
import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.swing.JOptionPane;

/**
 *
 * @author almamy
 */
public class PasswordForget extends javax.swing.JFrame {
    private final String addresse = "burusomali@gmail.com";
    private final String password = "octrithhpkcjzpcw";
    private String cd;
    
    /**
     * Creates new form PasswordForget
     */
    public PasswordForget() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.codeField.setEnabled(false);
        this.codeSender.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        emailforgotField = new javax.swing.JTextField();
        sendBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        codeSender = new javax.swing.JButton();
        codeField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(51, 51, 51));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        emailforgotField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailforgotFieldActionPerformed(evt);
            }
        });
        getContentPane().add(emailforgotField, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 205, -1));

        sendBtn.setBackground(new java.awt.Color(51, 51, 51));
        sendBtn.setForeground(new java.awt.Color(255, 255, 255));
        sendBtn.setText("SEND");
        sendBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendBtnActionPerformed(evt);
            }
        });
        getContentPane().add(sendBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 205, -1));

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Email");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 66, -1));

        jLabel2.setBackground(new java.awt.Color(0, 102, 204));
        jLabel2.setFont(new java.awt.Font("Liberation Sans", 1, 20)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Password Forget");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 205, -1));

        jLabel3.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Code");
        jLabel3.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 66, -1));

        codeSender.setBackground(new java.awt.Color(51, 51, 51));
        codeSender.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        codeSender.setForeground(new java.awt.Color(225, 225, 225));
        codeSender.setText("VALIDATE");
        codeSender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codeSenderActionPerformed(evt);
            }
        });
        getContentPane().add(codeSender, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, 205, -1));
        getContentPane().add(codeField, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, 205, -1));

        jLabel4.setBackground(new java.awt.Color(51, 51, 51));
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 330));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sendBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendBtnActionPerformed
        // TODO add your handling code here:
        
                 File file = new File("/home/almamy/Documents/MyProject/Buruso/src/main/java/modele/authentification/LogUp.txt");
                 if(file.exists()){
                     
                    Scanner sc;
                     try {
                         sc = new Scanner(file);
                         String str = "";
                         
                       String pass= this.emailforgotField.getText();
                        while(sc.hasNext()){
                        String mot = sc.next();

                        if(mot.equals(pass)){
                            str = mot;
                        }
                    }   
                    System.out.print("Str valeur: " + str);
                    if(str.equals(pass)){
                        Random rand = new Random();
                        int code = rand.nextInt(999999);
                        cd = Integer.toString(code);
                        PasswordForget forget = new PasswordForget();
                        forget.envoyer(code, pass);
                       
                        this.sendBtn.setEnabled(false);
                        this.emailforgotField.setEnabled(false);
                        this.codeField.setEnabled(true);
                        this.codeSender.setEnabled(true);
                    }else{
                        JOptionPane.showMessageDialog(this, "Your have'nt the compte in Buruso service");
                    }
                     } catch (FileNotFoundException ex) {
                         Logger.getLogger(PasswordForget.class.getName()).log(Level.SEVERE, null, ex);
                     }
                    
                 }
    }//GEN-LAST:event_sendBtnActionPerformed

    private void emailforgotFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailforgotFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailforgotFieldActionPerformed

    private void codeSenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codeSenderActionPerformed
        // TODO add your handling code here:
       if(this.cd.equals(this.codeField.getText())){
            PasswordChanger Pwc = new PasswordChanger();
            Pwc.show();
            dispose(); 
       }else{
           System.err.print(cd);
       }
    }//GEN-LAST:event_codeSenderActionPerformed

    public void envoyer(int codes, String passs) {
            // Etape 1 : Création de la session
            Properties props = new Properties();
            props.put("mail.smtp.auth", "true");
            props.put("mail.smtp.starttls.enable","true");
            props.put("mail.smtp.host","smtp.gmail.com");
            props.put("mail.smtp.port","587");
            Session session = Session.getInstance(props,
            new javax.mail.Authenticator() {
                @Override
                protected PasswordAuthentication getPasswordAuthentication() {
                return new PasswordAuthentication(addresse, password);
                }
            });
            System.out.println(passs);
            try {
            // Etape 2 : Création de l'objet Message
                Message message = new MimeMessage(session);
                System.out.println(passs);
                message.setFrom(new InternetAddress("bursomali@gmail.com"));
                message.setRecipients(Message.RecipientType.TO,
                InternetAddress.parse(passs));
                
                message.setSubject("Test email");
                message.setText(""+codes);
                // Etape 3 : Envoyer le message
                Transport.send(message);
                System.out.println(passs);
                System.out.println("Message_envoye");
                System.out.println(passs);
            } catch (MessagingException e) {
             throw new RuntimeException(e);
            } 
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PasswordForget.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PasswordForget.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PasswordForget.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PasswordForget.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PasswordForget().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField codeField;
    private javax.swing.JButton codeSender;
    private javax.swing.JTextField emailforgotField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton sendBtn;
    // End of variables declaration//GEN-END:variables
}
